### ISSUE TITLE
Write LF and HF Tag

### ISSUE THREAD

**Issue by Warborn123** [GameTec-live/ChameleonUltraGUI#107]
Hi, I was just wondering if the chameleon ultra is able to write tags, especially LF tag, since phones are not able to do that. Thanks.

**Comment by Foxushka** [comment]
Possible, LF was implemented yesterday, not everything will be done in one day

**Comment by GameTec-live** [comment]
it should be able to, but not yet, afaik it isnt even supported in firmware

**Comment by Foxushka** [comment]
Supported

**Comment by Foxushka** [comment]
writeEM410XtoT55XX/mf1WriteBlock

**Comment by ctschach** [comment]
Any updates on Write support? That would be a nice (an essential) feature to have...

**Comment by GameTec-live** [comment]
> Any updates on Write support? That would be a nice (an essential) feature to have...

Its activly being worked on, but freetime is limited...
