### ISSUE TITLE
Add language settings (Crowdin)

### ISSUE THREAD

**Issue by jkh0kr** [GameTec-live/ChameleonUltraGUI#116]
I want to translate it into each country's language.

Is it difficult to add a language file in multi-language without adding the language to the source?

**Comment by GameTec-live** [comment]
> I want to translate it into each country's language.
> 
> Is it difficult to add a language file in multi-language without adding the language to the source?

ill look into it and altough it would make sense to have multiple languages, i assume that most people know english, so its going pretty low on the list...

**Comment by Foxushka** [comment]
Crowdin integration is worth it, we will accept PR if someone will do it

**Comment by aruznieto** [comment]
> Crowdin integration is worth it, we will accept PR if someone will do it

I am trying to do that but It seems that you need premium Crowdin account to do the deliver of the traductions.

**Comment by GameTec-live** [comment]
you dont even need crowdin, flutter supports it nativly https://docs.flutter.dev/ui/accessibility-and-localization/internationalization

**Comment by aruznieto** [comment]
> you dont even need crowdin, flutter supports it nativly https://docs.flutter.dev/ui/accessibility-and-localization/internationalization

Yes, know. I am doing that, I mention Crowdin because @Foxushka says that

**Comment by GameTec-live** [comment]
yeah, relying on a 3rd party isnt the best idea

**Comment by aruznieto** [comment]
> yeah, relying on a 3rd party isnt the best idea

👍🏻. [Here](https://github.com/aruznieto/ChameleonUltraGUI/tree/crowdin-integration) you can follow how am I doing it. And [Here](https://crowdin.com/project/chamaleonultragui) is the Crowdin project (only to allow people to translate it, but the integration is manual)

**Comment by Foxushka** [comment]
I've already created it 2 days ago: https://crowdin.com/project/chameleon-ultra-gui

**Comment by Foxushka** [comment]
> The aren't any string right

I just done some tests, currently busy with macOS/iOS releases. If you need to add some languages or invite you to our project ping me

**Comment by aruznieto** [comment]
If you invite me as admin I can manage it

> > The aren't any string right
> 
> I just done some tests, currently busy with macOS/iOS releases. If you need to add some languages or invite you to our project ping me

If you invite me as admin I can manage it

**Comment by Foxushka** [comment]
I unfortunately can't add you as member or developer on free account. Should I export and import strings from your project?

**Comment by aruznieto** [comment]
> I unfortunately can't add you as member or developer on free account. Should I export and import strings from your project?

I have joined to your project, maybe now you can edit my perms

**Comment by Foxushka** [comment]
> > I unfortunately can't add you as member or developer on free account. Should I export and import strings from your project?
> 
> I have joined to your project, maybe now you can edit my perms

"Upgrade to add managers. Managers can create tasks, assign translators, manages glossaries and translation memories, and set up integrations to automate localization." even if I try to add you as developer

**Comment by aruznieto** [comment]
> > > I unfortunately can't add you as member or developer on free account. Should I export and import strings from your project?
> 
> > 
> 
> > I have joined to your project, maybe now you can edit my perms
> 
> 
> 
> "Upgrade to add managers. Managers can create tasks, assign translators, manages glossaries and translation memories, and set up integrations to automate localization." even if I try to add you as developer
> 
> 

Ok, when I finish the translation on my project i will send you the files.

**Comment by aruznieto** [comment]
> I unfortunately can't add you as member or developer on free account. Should I export and import strings from your project?


I think that is better if you join to my project, because if I need to add a string I will not be able to edit on your project.

**Comment by Foxushka** [comment]
To accept translation PR entire app should be translated. You don't need to add new strings after that. If someone will need new strings they could ask in PR with their changes

**Comment by aruznieto** [comment]
> To accept translation PR entire app should be translated. You don't need to add new strings after that. If someone will need new strings they could ask in PR with their changes

If you add new strings I need to add it to the translation.  I already translate all texts on app

**Comment by Foxushka** [comment]
I still don't understand your point, if I need to add new strings, I add them to our project, then others (and you) can translate them
