### ISSUE TITLE
Chameleon Ultra Bricked

### ISSUE THREAD

**Issue by Warborn123** [GameTec-live/ChameleonUltraGUI#122]
Hi, I think I Bricked my CU after choosing the Flash FW from .zip, the two green led are flashing and the GUI told me it's in DFU mode & firmware is corrupted, and it won't work after I click the update firmware option. If there's anyway to fix this? Thanks.

**Comment by Foxushka** [comment]
On which OS you tried to flash it? Try to flash again

**Comment by Foxushka** [comment]
What android phone you have? Model + Android version

**Comment by GameTec-live** [comment]
> What android phone you have? Model + Android version

im telling you, its the stupid BLE bug with it not recognizing that its supposed to flash a fw

**Comment by Foxushka** [comment]
As bug explained to me by @GameTec-live I will try to reproduce it later. You can always re-flash on Linux/macOS/Windows

**Comment by GameTec-live** [comment]
yes, its a stupid bug with BLE library. (Disabling Bluetooth could work, maybe)

> > > What android phone you have? Model + Android version
> > 
> > 
> > im telling you, its the stupid BLE bug with it not recognizing that its supposed to flash a fw
> 
> I'm not connecting my Chameleon using Bluetooth, I used a C to C cable, since update the firmware via Bluetooth doesn't seems too risky.

**Comment by Foxushka** [comment]
ahaahhaah windows

**Comment by Foxushka** [comment]
Check integrity of files `sfc /scannow` and  `DISM /Online /Cleanup-Image /RestoreHealth`

**Comment by GameTec-live** [comment]
> > ahaahhaah windows
> 
> You also mentioned macOs, I actually have a M1 MacBook, but I can't find any package that can run on macOS, should I install the lincu version?

latest GH actions should have mac builds, altough linux is recommended, yes...

**Comment by Foxushka** [comment]
> latest GH actions should have mac builds, altough linux is recommended, yes...

No, they won't work as they aren't signed (apple...). But app should work fine if you compile it yourself, no errors

**Comment by Foxushka** [comment]
Try to flash with https://play.google.com/store/apps/details?id=no.nordicsemi.android.dfu

**Comment by GameTec-live** [comment]
> > Try to flash with https://play.google.com/store/apps/details?id=no.nordicsemi.android.dfu
> 
> It seems like the app has a new BLE connection to flash the firmware, but because my Chameleon is brick, the BLE doesn't work, so my phone can't find it... Also, what .zip should I use? The reason it was bricked is because I downloaded the .zip from (https://github.com/RfidResearchGroup/ChameleonUltra/releases/tag/dev) and flashed it to my Chamelon, maybe I shouldn't use it?

latest gh actions or factory fw?

**Comment by Foxushka** [comment]
> It seems like the app has a new BLE connection to flash the firmware, but because my Chameleon is brick, the BLE doesn't work

BLE will work in DFU in any case, you can't brick DFU unless you are flashing with SWD (hint - requires external hardware, you don't). Try restarting your phone and chumleon, maybe shorting battery will do its trick (@GameTec-live done it, I don't suggest it, but you probably don't have any other way)

**Comment by Foxushka** [comment]
Android flashing issues should be fixed in #135
