### ISSUE TITLE
[Bug] Android permission missing for Serial

### ISSUE THREAD

**Issue by F9Alejandro** [GameTec-live/ChameleonUltraGUI#123]
Please see image below for more context.
![Screenshot_20230820_094830.jpg](https://github.com/GameTec-live/ChameleonUltraGUI/assets/1888010/c1ba293d-b158-4843-97e5-ea73b190dd10)

![Screenshot_20230820_095010_Permission controller.jpg](https://github.com/GameTec-live/ChameleonUltraGUI/assets/1888010/3bfdddfd-daa5-43b8-806a-b513ca3f675e)

**Comment by Foxushka** [comment]
We have different error screen in current release (this belong to web), are you sure you downloaded app from main branch or Google Play?

**Comment by F9Alejandro** [comment]
Main branch from gh actions.

**Comment by Foxushka** [comment]
Install from google play

**Comment by Foxushka** [comment]
And if you want help don't lie next time as I definitely know that this error screen belongs to pending web PR

**Comment by F9Alejandro** [comment]
Sorry didn't mean to lie. It isn't like I didn't download the first gh action release that showed up or anything with an apk build....

**Comment by Foxushka** [comment]
Enable debug menu in settings and show its screenshot

**Comment by Foxushka** [comment]
My bad, no changes there. As I said try to download from google play
