### ISSUE TITLE
MFkey32 is not working

### ISSUE THREAD

**Issue by Warborn123** [GameTec-live/ChameleonUltraGUI#126]
Hi guys, it seems like the MFkey32 attack is not working now (since the update 2 days ago I think), I'm using the latest firmware & GUI (6073b5c firmware and 853def0 GUI), my phone is still S23 Ultra. Thanks for the help!

![Screenshot_20230821_191725](https://github.com/GameTec-live/ChameleonUltraGUI/assets/54515949/cbadf954-18e8-4d31-9a3e-20ba771f5682)

**Comment by GameTec-live** [comment]
restart app and reconnect chameleon

**Comment by Foxushka** [comment]
Will look into it

**Comment by GameTec-live** [comment]
> > restart app and reconnect chameleon
> 
> Hi, I tried that, it still shows the same error message. Thanks.

hm, okay... Ill just ask the default stuff:
OS:
If phone, which model:
App version:
FW  version:

**Comment by Foxushka** [comment]
Error verified
