### ISSUE TITLE
Error: RangeError (index): Invalid value: Valid value range is empty: 0

### ISSUE THREAD

**Issue by strasharo** [GameTec-live/ChameleonUltraGUI#133]
I'm getting the following exception when I try to connect to the Chameleon Ultra on the home page:

![Screenshot at 2023-08-22 13-14-03](https://github.com/GameTec-live/ChameleonUltraGUI/assets/3337997/ffa2ef71-0d08-457a-ad9b-0f3041ff3454)
Using it on latest Fedora 38.

**Comment by Foxushka** [comment]
@GameTec-live you used new firmware methods without try catch?

**Comment by GameTec-live** [comment]
> @GameTec-live you used new firmware methods without try catch?

i didnt touch the homepage, you touched it

**Comment by osulivanDE** [comment]
Same Issue here with fresh unpacked Chameleon Ultra + Android App

**Comment by GameTec-live** [comment]
> Same Issue here with fresh unpacked Chameleon Ultra + Android App

yeah its an outdated fw version which doesnt have some commands. @Foxushka added? changed? a status display that uses those commands, forgot a try catch and thus the homepage crashes

**Comment by osulivanDE** [comment]
Same for me, the only thing my Android App wanted do flash my Chameleon Ultra with some kind of "Chameleon Lite" Firmware when i tied to update it. I disconnected BT fast.

**Comment by GameTec-live** [comment]
> Same for me, the only thing my Android App wanted do flash my Chameleon Ultra with some kind of "Chameleon Lite" Firmware when i tied to update it. I disconnected BT fast. 

it doesnt work over bt (flashing)

**Comment by osulivanDE** [comment]
ah, great. So no accidentally wrong FW flashing. Thanks
