### ISSUE TITLE
Latest Firmware update broke BLE connection?

### ISSUE THREAD

**Issue by Warborn123** [GameTec-live/ChameleonUltraGUI#166]
Hi guys, I think the lastest firmware update (845cae9) broke the BLE, now I can't connect it using BLE (Android 13, S23 Ultra). The GUI I'm using is the latest as well (7612324). 

![Screenshot_20230828_123142](https://github.com/GameTec-live/ChameleonUltraGUI/assets/54515949/5d5ced07-2b12-43c9-8dd0-154412b322ae)

**Comment by GameTec-live** [comment]
someone had that error in the discord i think, clear all bonds on phone and device and try again

**Comment by GameTec-live** [comment]
its a error in the BLE library, so beyond our control...

**Comment by brianbgarber** [comment]
I'm getting a pairing pin request. 0000 and 1234 don't work for me.

**Comment by nieldk** [comment]
Pairing never worked on my device. Might be BLE library, but i think this should be rolled back until it works as intended.

**Comment by GameTec-live** [comment]
it indeed is a thing with the new pairing thing, as suggested on the discord, there should be settings for no ble, plain ble, secure ble or whatever...

**Comment by Foxushka** [comment]
@GameTec-live please enable discussions for such questions

**Comment by Msprg** [comment]
> > I'm getting a pairing pin request. 0000 and 1234 don't work for me.
> 
> It's 123456

TYSM I've been looking for this! Here's hoping we'll get some documentation in the official repo soon

**Comment by BushmanK** [comment]
@Msprg, https://github.com/RfidResearchGroup/ChameleonUltra/issues/108
