### ISSUE TITLE
DFU broken in iPhone App

### ISSUE THREAD

**Issue by nbdys** [GameTec-live/ChameleonUltraGUI#181]
After trying to do a Firmware update with the iPhone App, Cham is stuck in DFU mode. Tried several times to flash again, still same thing. It starts flashing, green lights then blue lights, after a few seconds LEDs go dark and Cham to standby. App still says: wait it’s updating.

**Comment by Foxushka** [comment]
Should be fixed in #172, currently under Apple's review
