### ISSUE TITLE
Slot info in slot settings in slot manager 

### ISSUE THREAD

**Issue by Foxushka** [GameTec-live/ChameleonUltraGUI#182]
Button at top of slot settings with pencil icon (edit)

Should show UID/SAK/ATQA for HF (missing FW) and UID for LF
Editable ^ data + changing slot type
Download mifare classic dump from slot (save to saved cards), save lf to slot too

**Comment by Foxushka** [comment]
No, slot should be editable too

**Comment by GameTec-live** [comment]
no

**Comment by Foxushka** [comment]
yes

**Comment by cyber-vi-king** [comment]
I agree, setting basics per slot are useful (also just viewing the current UOD/SAK/ATQA would help already). 

For some locks there is no need to set a dump if the uid is enough.

**Comment by GameTec-live** [comment]
https://github.com/GameTec-live/ChameleonUltraGUI/tree/slot-editing
Waiting for fw

**Comment by Foxushka** [comment]
Firmware part finished in https://github.com/RfidResearchGroup/ChameleonUltra/pull/104
