### ISSUE TITLE
Some appearence issues on Android smartphone

### ISSUE THREAD

**Issue by spp2000** [GameTec-live/ChameleonUltraGUI#214]
Hi, all the pages looks fine now, but there are 4 that need some improvement in my case. I show you:

**Text size is much bigger than the others (bigger than title)**

![1](https://github.com/GameTec-live/ChameleonUltraGUI/assets/42212032/d4c5ec05-1322-47f7-8ce6-185cd1527924)

**Truncated buttons**

![3](https://github.com/GameTec-live/ChameleonUltraGUI/assets/42212032/e9981457-3096-4ca9-a406-61a88676e6d0)

**Truncated text** (the slot nick can be even longer than this)

![2](https://github.com/GameTec-live/ChameleonUltraGUI/assets/42212032/d5ffed1d-1f42-42c8-9062-daca6bdb375e)

**Truncated text and sectors**

![4](https://github.com/GameTec-live/ChameleonUltraGUI/assets/42212032/f8a2df86-a743-46dc-8d2a-9b0fc6eea49d)

Thank you

**Comment by Foxushka** [comment]
Should I move this to https://github.com/GameTec-live/ChameleonUltraGUI/issues/188? Maybe. Issues are known and should be fixed sometime. Current priority is to implement everything important, and only then move on to UI fixes.

**Comment by spp2000** [comment]
Hi, just to inform you that truncated button in Slot Settings (2nd picture) now are ok! Thanks

**Comment by spp2000** [comment]
"Truncated text and sectors" (4th picture) both solved! Nice layout.

But, after checking keys with some unknown, "Dump partial data" button is partially truncated

**Comment by GameTec-live** [comment]
Its because of this fixed spacer: https://github.com/GameTec-live/ChameleonUltraGUI/blob/de2513cb75a0e7b9d7606e4bb71073d07dc088da/chameleonultragui/lib/gui/page/read_card.dart#L808

**Comment by Foxushka** [comment]
@spp2000 should be fine on build 305+. Other still depends on #200

**Comment by spp2000** [comment]
> @spp2000 should be fine on build 305+. Other still depends on #200

Yes, now the two buttons are complete and well centered!! Thanks
Also the 1st picture (huge text) depends on #200?

**Comment by Akisame-AI** [comment]
The saved cards page seems to break when I add in my scaling fixes to it. Saved cards should have a lot smaller letter type already though. 
I will try scaling in a different way and submit it. I have a bit of free time today.

**Comment by Akisame-AI** [comment]
Okay, scaling issues should be a lot better now. Not prefect but at least usable. 
These scaling things only apply on very narrow windows. 
![image](https://github.com/GameTec-live/ChameleonUltraGUI/assets/61940251/03f9c79f-98d3-4cd8-8a59-aa88c303e7cd)

![image](https://github.com/GameTec-live/ChameleonUltraGUI/assets/61940251/79b94646-74e5-4c63-9ac2-faf1c86ca2e7)

![image](https://github.com/GameTec-live/ChameleonUltraGUI/assets/61940251/16028ccd-9bca-44e2-b0e6-931cf8d304c4)

![image](https://github.com/GameTec-live/ChameleonUltraGUI/assets/61940251/e8436740-0f1e-476e-8b02-57c0b9df6496)
