### ISSUE TITLE
Recover keys (mfkey32) timeout on iOS

### ISSUE THREAD

**Issue by krissen** [GameTec-live/ChameleonUltraGUI#218]
Recovering keys through collected nonces works fine on Android. 

When attempting on iOS, recovery timeouts `waiting for response for command 4005`. 

![image](https://github.com/GameTec-live/ChameleonUltraGUI/assets/2943684/da082854-1ddf-43d1-8d0f-9378c888a021)

Connected through secure BLE. Connection good, everything else works fine. Only key recovery timeouts, and only on iOS.

**Comment by krissen** [comment]
Hold up. Might not be particular to GUI.

In cli, `hf detection count` (for instance) also gives me the same error:

```
TimeoutError: CMD 4005 exec timeout
```

Over serial. Nevertheless, on Android (BLE, like iOS) *it works.*

**Comment by GameTec-live** [comment]
> Hold up. Might not be particular to GUI.
> 
> In cli, `hf detection count` (for instance) also gives me the same error:
> 
> ```
> TimeoutError: CMD 4005 exec timeout
> ```
> 
> Over serial. Nevertheless, on Android (BLE, like iOS) _it works._

maybe talk to the firmware devs then?

**Comment by krissen** [comment]
> maybe talk to the firmware devs then?

Naturally. Hadn’t checked with cli prior to submitting the issue, only iOS and Android. Given that one worked and the other didn’t, a GUI issue seemed more plausible. 

Now it doesn’t. 

Let’s close the issue for now at least.
