### ISSUE TITLE
Changing the default Bluetooth pin breaks the connection to the device

### ISSUE THREAD

**Issue by georgikoemdzhiev** [GameTec-live/ChameleonUltraGUI#224]
Hello, 

I tried changing the default Bluetooth pin (12345) via the app but after pressing save, I am no longer able to pair with the ChamelionUltra. It keeps prompting me to type in the password. 

Steps I followed:
1. I paired successfully with the default password 12345
2. I went to settings and changed the password
3. The device disconnected (I think that's expected)
4. I trued to pair the device again using the app
5. I was prompted to enter a password, I entered the new password
6. The ChamelionUltra icon appeared in the "Connect" screen
7. I selected it

From here I entered an endless look going between steps 5 to 7.

Could you please share any steps on how to pair the device again?

**Comment by GameTec-live** [comment]
you probably need to delete the bonds / unpair? https://github.com/RfidResearchGroup/ChameleonUltra/blob/main/docs/troubleshooting.md#ble

**Comment by Foxushka** [comment]
![image](https://github.com/GameTec-live/ChameleonUltraGUI/assets/135865149/5692f7c0-dc2a-4f40-bbfc-576be30917fa)
🙄

**Comment by Foxushka** [comment]
![image](https://github.com/GameTec-live/ChameleonUltraGUI/assets/135865149/4f82ea68-b7a7-49b9-a772-6018ba90c30b)
Required on change password too... Eh.

**Comment by Foxushka** [comment]
![image](https://github.com/GameTec-live/ChameleonUltraGUI/assets/135865149/0d117ae0-5aed-42f3-b121-5fcd48f1caa9)
