### ISSUE TITLE
Disable BLE pairing

### ISSUE THREAD

**Issue by spp2000** [GameTec-live/ChameleonUltraGUI#225]
Can you add the option to disable BLE pairing soon? For "soon" I mean **before** fixing all BLE issues. In this way we can choose to disable the PIN and we can avoid many crashes and/or bluetooth setting reset every time the firmware is updated. It's really boring having to do it all the time. When BLE is mature enough, it will be a pleasure to use pairing. Thank you!!

**Comment by GameTec-live** [comment]
~~Complain to the firmware team~~
Were dependent on firmware, please redirect your request to there:
https://github.com/RfidResearchGroup/ChameleonUltra
