### ISSUE TITLE
Mifare Classic 1K recover key problem

### ISSUE THREAD

**Issue by alonegr** [GameTec-live/ChameleonUltraGUI#267]
Hi everyone, with both the Android and Windows apps updated to the latest version available, it is impossible for me to recover the keys for a normal Mifare Classic 1k while it works if I use a copy on a magic card cloned with Promark the Chameleon Ultra is updated to the latest version. Thank you
![screen](https://github.com/GameTec-live/ChameleonUltraGUI/assets/58873146/b68a2cd7-33d8-4820-a1ac-652b8ec6dd45)

**Comment by GameTec-live** [comment]
what is the output of the pm3s HF search? because if the card uses hardnested it isnt supporred yet.

**Comment by Foxushka** [comment]
Staticnested/hardnested not supposed on firmware side. Nothing we can do. Create issue on Chameleon Ultra firmware repo
