### ISSUE TITLE
Improve key finding in dictionary

### ISSUE THREAD

**Issue by maul3x** [GameTec-live/ChameleonUltraGUI#275]
**Describe the bug**
When I try to read a card with a big dictionnary (1600keys), it's very slow. But the key is the same between each sector, it would be fast after the first key was find ?

**Comment by GameTec-live** [comment]
> it would be fast after the first key was find ?

what?
Im just gonna assume you mean that one should cache the first found key and try it on the next sector, of that fails start again from dict. if thats what you mean itd make sense, yeah, not a bad idea

**Comment by maul3x** [comment]
YES ! It's exactly what I mean.
(Sorry for my english)

**Comment by Foxushka** [comment]
This adds additional level of complexity to key checking. I don't sure we are ready for it

**Comment by Foxushka** [comment]
Will try to fit in 1.0.0 release
