### ISSUE TITLE
feat: More battery info

### ISSUE THREAD

**Issue by GameTec-live** [GameTec-live/ChameleonUltraGUI#295]
when clicking on the battery icon (homepage) popup a window with more info (Voltage, Precentage, maybe charge cycles if firmware implements it). (REFETCH for most uptodate info!)

**Comment by Foxushka** [comment]
Useless

**Comment by GameTec-live** [comment]
no, knowing the real voltage, etc, directly from firmware isnt useles, says more than a few pixels lol...
also; @doegox asked nicely for it

**Comment by Foxushka** [comment]
if @doegox is implementing that then yes

**Comment by doegox** [comment]
voltage and percentage are already available from the fw
