### ISSUE TITLE
New visualization issues

### ISSUE THREAD

**Issue by spp2000** [GameTec-live/ChameleonUltraGUI#316]
**Issue n.1**
On Android the card type and the 3 icons are on the same row, so the text is truncated.

![android](https://github.com/GameTec-live/ChameleonUltraGUI/assets/42212032/1fcd4534-a7a7-4862-836b-2583a5af819e)

In Windows (also using a similar aspect ratio) they are placed on two rows, so it's ok

![windows](https://github.com/GameTec-live/ChameleonUltraGUI/assets/42212032/6253a93a-5a68-4f94-a3dd-4b29f93deb2c)

**Issue n.2** (not really an issue)
I would delete the spaces between the bytes because they are not required when you paste them elsewhere (and could be tedious to remove them):

![keysspaces](https://github.com/GameTec-live/ChameleonUltraGUI/assets/42212032/87fdb414-30ef-4706-9675-a225d108bc11)

**Comment by GameTec-live** [comment]
n1 is indeed a real issue, on android its wierdly not being moved down below... n2 is alrdy fixed / having a space or not is a personal preference thing...
