### ISSUE TITLE
Proposal: split "Saved cards" into "Saved cards" & "Saved dictionaries"

### ISSUE THREAD

**Issue by spp2000** [GameTec-live/ChameleonUltraGUI#318]
Immagine that you have about 10 saved cards and 6-7 dictionaries (this is my real usage, not so unusual).
On a smartphone you can see only the first two cards and the first two dictionaries, forcing you to scroll a lot to find the right ones in that little space.
When, in the next releases, we will have more rows for cards (nick, card type, icons, ID/UID) and for dictionaries (name, key count, icons), probably we can see only one card/dictionary at a time and we have to scroll precisely to center the one that we need.
My suggestion is to split "Saved Cards" into 2 pages: "Saved cards" and "Saved dictionaries"

**Comment by GameTec-live** [comment]
on my phone i see more than 2, but yes, this very phone size dependent. We wont add any more rows, you got name and type, thats it. for more info you tap on the card/dict... i do wonder though, how often are you editing dictionaries, that finding them from a list is a big problem lol
Most of the time a search just opens...
Splitting then in 2 pages just wouldnt fit imo...
