### ISSUE TITLE
Add support for more TAG types

### ISSUE THREAD

**Issue by bagbagbag91** [GameTec-live/ChameleonUltraGUI#320]
I'm using Chameleon Ultra for a few weeks. I'm very happy that we already have such a good GUI. 
So far I've managed to successfully clone `EM410X` and `Mifare Classic 1K` tag types and It worked lie a charm.

But recently I took a TAG from my friend and while trying to clone it here is what I've got:

![screenshot_chameleon_ultra](https://github.com/GameTec-live/ChameleonUltraGUI/assets/28864541/f35b380c-34c7-4153-83c1-3a4bb2e796b1)

Would be really great if you add support for more TAG types.

I know that Chameleon Ultra supports a lot of HF and LF TAG types, [here](https://github.com/RfidResearchGroup/ChameleonUltra/blob/main/docs/technical_whitepaper.md#high-frequency-reader) is a full list of supported TAG types.

**Comment by GameTec-live** [comment]
it doesnt support "a lot of tag types", if it doesnt say "supported" in all 3 collumns, we cant implement it. And if your talking bout ntag, #278

**Comment by bagbagbag91** [comment]
I see, thank you 🙏
