### ISSUE TITLE
API request fail, param error

### ISSUE THREAD

**Issue by Markus-HL** [GameTec-live/ChameleonUltraGUI#337]
the command "hw slot list" end with the message "API request fail, param error" after Slot 3
See picture:

![Bildschirmfoto_2023-10-14_17-12-05](https://github.com/GameTec-live/ChameleonUltraGUI/assets/142630451/3d2833cb-ce70-4f56-8d7d-833f31077ccb)

**Comment by GameTec-live** [comment]
Sorry, but for CLI issues, this is the wrong repository / issue tracker...
Please reopen it on:
https://github.com/RfidResearchGroup/ChameleonUltra

**Comment by Foxushka** [comment]
🤣
