### ISSUE TITLE
Saving Found Keys

### ISSUE THREAD

**Issue by tkerby** [GameTec-live/ChameleonUltraGUI#344]
If you work in or are visiting a facility you may have access to a keycard you have been given (eg an office access token or hotel room door lock card). You usually have unfettered access to this for long enough to easily run a nested attack. 

If you then want to clone other cards, you need the quickest possible read and should be able to use a history of found keys within the app (ie automatically saved to a personal dictionary). Perhaps with the ability to select all the history or a recent day, week, month or year for speed. 

While I know it's not totally an app feature it would also be great to see the Chameleon one button clone to be able to 'clone with keys'. Ie a means to save a key set to a slot in the app from an existing card and then those keys are used for a press and hold button clone. Might be one to think about for the future.

**Comment by GameTec-live** [comment]
adding a "save keys" button after keyrecovery on the read page has been a thought in the back of my head for s while, thats prob gonna happen...
