### ISSUE TITLE
Key dictionary file: mfc_defautlt_keys.dic where to download, the big guy guide

### ISSUE THREAD

**Issue by llliii0325** [GameTec-live/ChameleonUltraGUI#359]

**Comment by GameTec-live** [comment]
uhh, what? If you want to know where to download the mfc key file, its on the proxmark 3 repository (Altough the app has the most common keys built in under "Empty")
https://github.com/RfidResearchGroup/proxmark3/blob/master/client/dictionaries/mfc_default_keys.dic
