### ISSUE TITLE
Dude, how is the Chameleon ultra's front epoxy surface made? With a fixed model? Is it convenient to send a backward mold file? thank you

### ISSUE THREAD

**Issue by llliii0325** [GameTec-live/ChameleonUltraGUI#360]

**Comment by GameTec-live** [comment]
This is a issue tracker, not a instant messaging service, theres a discord for that...
Also; this isnt a GUI issue, heres the CU issue tracker: https://github.com/RfidResearchGroup/ChameleonUltra
