### ISSUE TITLE
MiFare 4K

### ISSUE THREAD

**Issue by aruznieto** [GameTec-live/ChameleonUltraGUI#367]
**Describe the bug**
Month ago (more or less) I could to read a dump a MiFare 4K card. Today I can't do it. The button of dump not appear

**Version info:**
 - OS: iOS 17
 - App build number: last (BETA)
 - Connection type: BLE
 - Chameleon firmware commit: v2.0.0-114-gec3c06

**Also required**:

- [x] - I've upgraded app to latest app version

- [x] - I've upgraded Chameleon firmware to latest version

- [x] - I've searched and verified that there is no already created issues

**Comment by Foxushka** [comment]
Record video

**Comment by GameTec-live** [comment]
tried on my iPad with a 4k Card, it works fine....
iOS: 17.0.3
App: 375
FW: 2.0.0-104-g299562b

**Comment by aruznieto** [comment]
In my MAC, iPhone and Windows it does not work. The technology is "Other"

**Comment by GameTec-live** [comment]
lemme try on windows, but are you sure its a MFC 4k?

**Comment by Foxushka** [comment]
Imagine not showing any screenshots and videos :roll_eyes:

**Comment by aruznieto** [comment]
Yes. Month ago works

—

Andrés Ruz Nieto

________________________________
De: GameTec-live ***@***.***>
Enviado: Sunday, October 29, 2023 6:13:03 PM
Para: GameTec-live/ChameleonUltraGUI ***@***.***>
Cc: RUZ NIETO, ANDRES ***@***.***>; Author ***@***.***>
Asunto: Re: [GameTec-live/ChameleonUltraGUI] MiFare 4K (Issue #367)


lemme try on windows, but are you sure its a MFC 4k?

**Comment by GameTec-live** [comment]
you sure you didnt switch up the cards, because my mifare classic 4k works... proxmark 3 `hf search` returns mfc 4k?

**Comment by aruznieto** [comment]
> Imagine not showing any screenshots and videos :roll_eyes: 

I am not at home now

**Comment by aruznieto** [comment]
> you sure you didnt switch up the cards, because my mifare classic 4k works... proxmark 3 `hf search` returns mfc 4k?

Is the university card... impossible switch

**Comment by Foxushka** [comment]
Do you remember ATQA/SAK?

**Comment by aruznieto** [comment]
> Do you remember ATQA/SAK?

SAK: 38
ATQA: 00 02

**Comment by GameTec-live** [comment]
> > Do you remember ATQA/SAK?
> 
> SAK: 38 ATQA: 00 02

my 4k got a SAK of 18, atqa is also 00 02 🤔 
Afaik 38 can be both mfc 4k and desfire, maybe thats why the app says tech other?
