### ISSUE TITLE
Cant select NTAG213/215/216 when setting up slot

### ISSUE THREAD

**Issue by p0ns** [GameTec-live/ChameleonUltraGUI#372]
**Describe the bug**
When I go into the Slot Manager, edit the current HF card and try to select any of the NTAG options, it reverts back to Unknown.

**To Reproduce**
1. Go to Slot Manager
2. Click on any of the slots settings button
3. In the Edit Slot Data display, select NTAG213/215/216
4. It reverts to Unknown

**Expected behavior**
NTAG options should be able to be selected.

**Screenshots**
<img width="912" alt="image" src="https://github.com/GameTec-live/ChameleonUltraGUI/assets/989743/a8aea6c2-69ff-4386-92cc-bc29a02a0268">

<img width="912" alt="image" src="https://github.com/GameTec-live/ChameleonUltraGUI/assets/989743/a9fa9c91-9f71-42dd-8c24-560e3a7f0e9d">

**Version info:**
 - OS: MacOS 14.0
 - App build number: 1.0.377 build 377
 - Connection type: USB
 - Chameleon firmware commit: g4d670f0

**Also required**:

- [x] - I've upgraded app to latest app version

- [x] - I've upgraded Chameleon firmware to latest version

- [x] - I've searched and verified that there is no already created issues

**Comment by GameTec-live** [comment]
hm, yes, this indeed seems to be a bug, but as firmware doesnt yet have full support for ntag anyways it isnt high priority for now...

**Comment by GameTec-live** [comment]
> Done on a purpose, firmware doesn't support it

ik fw doesnt support reading, but emulating too?
