### ISSUE TITLE
Can we unify the import and export json?

### ISSUE THREAD

**Issue by unknown10777** [GameTec-live/ChameleonUltraGUI#373]
I tried export the mifare classic 1k card to json, but the data inside is completely unreadable.
Can we unify the json data to [proxmark3's](https://github.com/RfidResearchGroup/proxmark3)  autopwn generated json?

**Comment by GameTec-live** [comment]
the CUGUI json contains a lot of data the pm3 json doesnt. afaik iceman wa ts to add a parser for that json too. The GUI does support importimg pm3 jsom though. And if you just want to read it, you can add back in the newlines in visual studio code by just saying "format document" in the command pallette...
