### ISSUE TITLE
Confirm delete card / dictionary

### ISSUE THREAD

**Issue by telephasicworkshop** [GameTec-live/ChameleonUltraGUI#390]
Suggestion: add option enabling prompt for confirmation before deleting saved cards and dictionaries.
That 🗑️ is close to the ⬇️ button 😄

**Comment by GameTec-live** [comment]
Im no big fan of much inbetween dialogs... Those will multiply by a lot if you want to delete 5 cards or so...
So this is a maybe. Not gonna close this yet...

**Comment by telephasicworkshop** [comment]
for sure it can get in the way sometimes and for some people, so it could be an option in the gui settings.

**Comment by GameTec-live** [comment]
> for sure it can get in the way sometimes and for some people, so it could be an option in the gui settings.

Yeah, was thinking about that... maybe some day...

**Comment by sarah1331sarah** [comment]
Or increase / distance the 🗑️ button from any other
