### ISSUE TITLE
Use ONLY custom dictionary

### ISSUE THREAD

**Issue by Stepzor11** [GameTec-live/ChameleonUltraGUI#393]
Every time it tries to read a tag, it cycles through its whole dictionary and the custom one (if chosen).
It would save a lot of time if I can chose to use ONLY a custom dictionary, without being forced to use also the system one.

**Comment by GameTec-live** [comment]
afaik if you select a custom dictionary it only uses the keys in said custom dictionary

**Comment by Stepzor11** [comment]
Nope.

I've tested and I can confirm that, as the text says, it is an "additional key dictionary" and it is used combined with the system one 😁

**Comment by GameTec-live** [comment]
![image](https://github.com/GameTec-live/ChameleonUltraGUI/assets/66077766/079fe6cb-4dfa-4222-82ee-88fed01f4bea)
code says otherwise

**Comment by GameTec-live** [comment]
maybe its performing key recovery

**Comment by Stepzor11** [comment]
> maybe its performing key recovery

Nope, key recovery is after the dictionary attack (or at least should be after, with the specific button) 😁

**Comment by GameTec-live** [comment]
> > maybe its performing key recovery
> 
> Nope, key recovery is after the dictionary attack (or at least should be after, with its specific button) 😁

yeah, right lol

**Comment by GameTec-live** [comment]
hm, indeed... Very wierd...
