### ISSUE TITLE
Cards downloaded from chameleon not saved correctly

### ISSUE THREAD

**Issue by VarChar42** [GameTec-live/ChameleonUltraGUI#400]
**Describe the bug**
Cards downloaded from the chameleon aren't saved correctly

**To Reproduce**
1. Downlaod Card from chameleon (in my case Mifare Classic 1K EV1)
2. Save card as json
3. Examine json
4. Everything is in the first sector.

**Expected behavior**
Data gets stored into its corresponding sector.

**Screenshots**
Unexpected:
![image](https://github.com/GameTec-live/ChameleonUltraGUI/assets/46874921/357c29d7-de79-44f5-ad16-fcc8d7a38937)
Expected
![image](https://github.com/GameTec-live/ChameleonUltraGUI/assets/46874921/f79aba74-5ae4-4807-8afb-c9899b2cba28)

**Version info:**
 - OS: Windows 11
 - App build number: 765
 - Connection type: USB

**Also required**:

- [x] - I've upgraded app to latest app version

- [x] - I've upgraded Chameleon firmware to latest version

- [x] - I've searched and verified that there is no already created issues 

**Additional context**
Despite this loading a card back onto the chameleon seems to work fine.

When viewing a downloaded card in the Hex Viewer (hex-editing branch) all data is also shown in Sector 0.

**Comment by GameTec-live** [comment]
Ive come to the conclusion that its a error in the rebuildCardSaveFromSlot function... (So not only json would be corrupt, but everything else too...)
Now the question is where...
https://github.com/GameTec-live/ChameleonUltraGUI/blob/edbd1343514ae69aaf08b946ff037edcd7714ab7/chameleonultragui/lib/gui/menu/slot_export.dart#L40C4-L40C4

**Comment by VarChar42** [comment]
Data gets returned like this from mf1GetEmulatorBlock. Maybe theres a problem with the chameleon firmeware.
![image](https://github.com/GameTec-live/ChameleonUltraGUI/assets/46874921/049f2280-6e70-4992-834d-87cde55a1883)

**Comment by GameTec-live** [comment]
> Data gets returned like this from mf1GetEmulatorBlock. Maybe theres a problem with the chameleon firmeware.
> ![image](https://github.com/GameTec-live/ChameleonUltraGUI/assets/46874921/049f2280-6e70-4992-834d-87cde55a1883)
> 

that'd be weird, but a possibility... Needs further investigation for sure...
