### ISSUE TITLE
Visualize found keys when reading card.

### ISSUE THREAD

**Issue by VarChar42** [GameTec-live/ChameleonUltraGUI#407]
**Is your feature request related to a problem? Please describe.**
When I want to see found keys I have to export them to a key dictionary.
There is no way to tell which key worked for each sector.

**Describe the solution you'd like**
Maybe show keys when hovering over ✅ or add a table below.

If we agree on a solution, I could implement it.

**Comment by GameTec-live** [comment]
hovering over the checkmark sounds like a good solution?

**Comment by GameTec-live** [comment]
So yeah, if you want to, feel free to add a tooltip... (Assuming it doesnt introduce any major changes lol)
