### ISSUE TITLE
Unable to run dark side attack 

### ISSUE THREAD

**Issue by sarah1331sarah** [GameTec-live/ChameleonUltraGUI#410]
Advise please 

If your unable to run a dark side attack how can I run another type of attack please

**Comment by GameTec-live** [comment]
Okay, some more information please... What are you trying to do? Did you skip the dictionary check? What app version are you running on? What OS? Steps to reproduce? ...

**Comment by sarah1331sarah** [comment]
Sorry fw 2.0 v2.0.0-128 gfefcde5 

version 1.0.0 build 811

no default keys 
Recover keys 

and resulted in 
![image](https://github.com/GameTec-live/ChameleonUltraGUI/assets/112808604/04c92df6-db08-4f00-a675-608773e13849)

if I check keys from directory I get no keys all X

**Comment by sarah1331sarah** [comment]
On another card (same campsite) I get sector 7 key b with all F’s but left to recover keys never recovers any after 12hours

**Comment by GameTec-live** [comment]
one of your cards probably isnt voulnerable to darkside then... (the other one taking an eternety, idk) why skip default keys 🤷

**Comment by sarah1331sarah** [comment]
I have no keys saved and default keys don’t hit either 

is it possible to run nested attack? When home I’ll try with offline nested with the card reader

**Comment by GameTec-live** [comment]
for nested you need atleast a few keys

**Comment by GameTec-live** [comment]
try using the larger pm3 dictionary, you can download it at their github:
https://github.com/RfidResearchGroup/proxmark3/blob/master/client/dictionaries/mfc_default_keys.dic

**Comment by sarah1331sarah** [comment]
sorry to sound thick how do i import the keys

**Comment by GameTec-live** [comment]
saved cards -> dictionaries -> + -> select the downloaded file

**Comment by sarah1331sarah** [comment]
With my mini I used to be able to sniff a key from the reader is that still possible

**Comment by GameTec-live** [comment]
not yet, still very early stages... you are able to do mfkey32 though... Please reference the Chameleon Ultra docs for more info on that...
