### ISSUE TITLE
When recovering keys under "write card", Write data stays grayed out after recovery

### ISSUE THREAD

**Issue by GameTec-live** [GameTec-live/ChameleonUltraGUI#411]
![image](https://github.com/GameTec-live/ChameleonUltraGUI/assets/83267603/683acdc2-4e24-413d-877c-53979dcd15f1)
And tried to write card have unknown keys, got keys using nested, and the button is blank. Is it expected? @Foxushka

_Originally posted by @unknown10777 in https://github.com/GameTec-live/ChameleonUltraGUI/issues/399#issuecomment-1868543764_

**Comment by Foxushka** [comment]
Definitely not expected

**Comment by VarChar42** [comment]
Cant reproduce with a Mifare Classic 1K. 🤔

**Comment by GameTec-live** [comment]
> Cant reproduce with a Mifare Classic 1K. 🤔

you need to run nested, dict recovery works fine
