### ISSUE TITLE
Cannot save card

### ISSUE THREAD

**Issue by lordrak007** [GameTec-live/ChameleonUltraGUI#422]
**Describe the bug**
Can not save readed card. 

**To Reproduce**
1. Read whole card
2. Click save, enter name
3. After click to save button nothing happens

If i use save only UID, uid is saved successfully. 

**Expected behavior**
Saved whole card

**Screenshots**
Nan

**Version info:**
 - OS: Android 13
 - App build number: 392
 - Connection type: BLE
 - Chameleon firmware commit: v2.0.0-128

**Also required**:

- [x] - I've upgraded app to latest app version

- [x] - I've upgraded Chameleon firmware to latest version

- [x] - I've searched and verified that there is no already created issues

**Comment by GameTec-live** [comment]
it says on the homepage...

**Comment by GameTec-live** [comment]
also; card saving works fine for me...

**Comment by lordrak007** [comment]
What it says on the homepage?
A have all up to date, and finally found FW version (edited in request).
Still, i cant save the card. When i try to read card, then click to save, enter name and nothing happens...

**Comment by GameTec-live** [comment]
weird, as said, saving works fine for me...
what card? mfc?
Also, what did you try to name it?

**Comment by lordrak007** [comment]
Yes, i am trying nfc Miface Clasic 1k. On windows working, on android nothing. Are there some lpgs which i can check or collect?

**Comment by GameTec-live** [comment]
yeah, you can try and perform saving a card with logging enabled... (a screenshot from the "read card" page, before you click on "save" cant hurt either)

To enable production logging:
1. Go to settings
2. Activate Debug mode
3. Go to Debug settings
4. Enable production logging

Then perform your actions, copy logs and dont forget to disable it again:
1. Return to Debug Settings
2. Click on "Copy logs to clipboard"
3. Paste them in github (please format them as a codeblock or upload a textfile)
4. Disable production logging
5. Press "Clear logs" (As leaving the logs in the "database" increases apps storage requirements and startup time)
6. (recommended) Disable Debug settings under Settings page

What does this option do? it writes all debug messages to disk (incase the app crashes) and allows you to copy them. This does mean the app will be a lot slower with prod logging enabled though.

**Comment by lordrak007** [comment]
I did it, here is problem with test card.
[log.txt](https://github.com/GameTec-live/ChameleonUltraGUI/files/13827443/log.txt)

**Comment by GameTec-live** [comment]
> I did it, here is problem with test card.
> [log.txt](https://github.com/GameTec-live/ChameleonUltraGUI/files/13827443/log.txt)
> 

ill look at it later, thx

**Comment by lordrak007** [comment]
No, Czech.
