### ISSUE TITLE
Debian-based (.deb) download link is broken

### ISSUE THREAD

**Issue by nkowallik** [GameTec-live/ChameleonUltraGUI#438]
**Describe the bug**
When attempting to download the .deb-based installer ([https://nightly.link/GameTec-live/ChameleonUltraGUI/workflows/build-app/main/linux-debian.zip](https://nightly.link/GameTec-live/ChameleonUltraGUI/workflows/build-app/main/linux-debian.zip)) the page linked to shows an HTTP 404 error code.

**To Reproduce**
1. Go to [https://github.com/GameTec-live/ChameleonUltraGUI](https://github.com/GameTec-live/ChameleonUltraGUI)
2. Click on either [Debian-based (.deb)](https://nightly.link/GameTec-live/ChameleonUltraGUI/workflows/build-app/main/linux-debian.zip) or the short link [https://chameleonultragui.dev/linux-debian](https://chameleonultragui.dev/linux-debian)
3. See error HTTP 404 stating 'Artifact 'linux-debian' not found for run #7457059397. '

**Expected behavior**
The click on the links should download a Debian installer or lead to a site, where a download link can be found.

**Screenshots**
![image](https://github.com/GameTec-live/ChameleonUltraGUI/assets/1642642/04c05d64-99f4-40d7-9150-2139c0c82fac)

**Version info:**
 - OS: Debian 12 (bookworm)
 - Firefox : Mozilla Firefox 115.6.0esr

**Comment by GameTec-live** [comment]
thanks, somehow the path just changed... pr is open...
