### ISSUE TITLE
Support for catalan language

### ISSUE THREAD

**Issue by gunther86** [GameTec-live/ChameleonUltraGUI#440]
I have started adding the resources for Catalan language in crowdin.

Creating this issue to let the developers know about it and to enable the language into the application.

**Comment by GameTec-live** [comment]
@aruznieto

**Comment by aruznieto** [comment]
It is supported, you only need to translate at least 70%, and say me to accept it

**Comment by gunther86** [comment]
Aha, thanks I will ping you once I reach 70%.
