### ISSUE TITLE
Error starting "chameleonultragui.exe" on Windows - file_saver_plugin.dll not found

### ISSUE THREAD

**Issue by viperxpi** [GameTec-live/ChameleonUltraGUI#45]
When starting the app getting and error as can be seen on screenshot. Windows11 Intel machine.

![error1](https://github.com/GameTec-live/ChameleonUltraGUI/assets/140005989/d2ff0e50-5bf4-4277-b9b5-3f7a8416610d)

**Comment by viperxpi** [comment]
Issue happens when using the installer. If installed using the installer, but copied the file from the "windows" artifacts - application starts. so it looks like the file was not packed to the installation package.

**Comment by GameTec-live** [comment]
what workflow run you used? main branch? (https://github.com/GameTec-live/ChameleonUltraGUI/actions/runs/5596108990)

**Comment by GameTec-live** [comment]
hm, indeed, can replicate the issue...

**Comment by GameTec-live** [comment]
[chameleonultragui-setup-win.zip](https://github.com/GameTec-live/ChameleonUltraGUI/files/12098774/chameleonultragui-setup-win.zip)
until the fix is merged, heres a manually built installer...

**Comment by viperxpi** [comment]
> what workflow run you used? main branch? (https://github.com/GameTec-live/ChameleonUltraGUI/actions/runs/5596108990)

yes. 3 of the latest , reproduced on all of them. but copying the missing file resolves the issue . Only remains to receive the hardware .

**Comment by GameTec-live** [comment]
fixed in #46
