### ISSUE TITLE
import name with dump automatically?

### ISSUE THREAD

**Issue by Sarah-1331** [GameTec-live/ChameleonUltraGUI#471]
**Is your feature request related to a problem? Please describe.**
no problem 

**Describe the solution you'd like**
when importing a dump to the saved cards can it automatically take the dump name its importing?

**Describe alternatives you've considered**
non

**Additional context**
cannot think of any additional

**Comment by GameTec-live** [comment]
what dump are you importing? if its a CUGUI dump it alrdy does that, if its a bin dump it doesnt, because that info isnt in a bin dump.
