### ISSUE TITLE
can you help with this card please 

### ISSUE THREAD

**Issue by Sarah-1331** [GameTec-live/ChameleonUltraGUI#472]
bit of copy paste from discord 

 I have a card MIFARE classic 1k and cloned to a magic 2 card works flawless every single time 

If I emulate it on the ultra the reader refuses to acknowledge it the rf I’d light is flashing I have tried several settings but nothing 

Any pointers

I should point out read and written using CUGUI app

someone mentioned timing? can this be adjusted at all my the end user? 

thanks again

**Comment by GameTec-live** [comment]
wrong github repo, open the issue on the Chameleon Ultra one instead, as this isnt a app but a firmware issue

**Comment by Sarah-1331** [comment]
Thank you
