### ISSUE TITLE
Firmware update fails

### ISSUE THREAD

**Issue by mindbreaker2** [GameTec-live/ChameleonUltraGUI#473]
When I try to update the firmware using the iOS cu gui app the download begins, then installation get stuck because the cu seems to shut off.

**To Reproduce**
1: connect to the cu 
2: use the look for update button

It used to work, I've updated the firmware multiple times but not working anymore

**Version info:**
 iOS 17.2.1
Cu gui up to date 
Cu firmware 2.0.0-131

**Comment by GameTec-live** [comment]
Yes, its a known issue... Apperenlty BLE DFU is broken. For now just update via a PC and USB please until theres time to fix it...

**Comment by mindbreaker2** [comment]
Yep, works like a charm using usb connection.

Hadn't seen any issue about it so I wanted to let everyone know. 

Thanks
