### ISSUE TITLE
Card Types not changable 

### ISSUE THREAD

**Issue by Riesenwombat** [GameTec-live/ChameleonUltraGUI#481]
**Describe the bug**
Can't Edit Cards to NTAG123 - 216

**To Reproduce**
1. Go to 'Saved Cards'
2. Click on 'Edit Card'
3. Click Card Type
4. Select NTAG
5. Type doesn't change

**Expected behavior**
Type should swap to NTAG.

**Screenshots**

**Version info:**
 - OS: Android 14
 - App build number: 1.0
 - Connection type: BLE
 - Chameleon firmware commit: 4747d38

**Also required**:

- [ x ] - I've upgraded app to latest app version

- [ x ] - I've upgraded Chameleon firmware to latest version

- [ x ] - I've searched and verified that there is no already created issues 

**Additional context**

**Comment by GameTec-live** [comment]
No you didnt... #372
