### ISSUE TITLE
Issue with Firmware Update 

### ISSUE THREAD

**Issue by Warborn123** [GameTec-live/ChameleonUltraGUI#490]
I got this error when upgrading to the latest firmware: "API rate limit exceeded for 50.114.59.3. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"

I'm on the latest Android App, current firmware is (v2.0.0-129-g3d8451a)

**Comment by GameTec-live** [comment]
You tried to update too often and the github api rate limited you? That's an achievement lol...
Just wait, should resolve itself
