### ISSUE TITLE
small key inconsistentency 

### ISSUE THREAD

**Issue by mitmarcus** [GameTec-live/ChameleonUltraGUI#510]
![Screenshot_20240814-232904.jpg](https://github.com/user-attachments/assets/c3be1086-a0e6-4967-af65-3d6f59723737)

![IMG_20240814_233021_479.jpg](https://github.com/user-attachments/assets/d8d20d64-0ef9-4b10-8a57-0892fdc5fda7)

Key type is not the same

**Comment by GameTec-live** [comment]
Because theres no mfc1k ev1, atleast there no need to as a ev1 is just a 1k with extra sectors, using a 2k has more sectors so we can fit them and the rest just gets ignored

**Comment by mitmarcus** [comment]
> Because theres no mfc1k ev1, atleast there no need to as a ev1 is just a 1k with extra sectors, using a 2k has more sectors so we can fit them and the rest just gets ignored

ah thank you! that explains it
