### ISSUE TITLE
Red LEDs flashing during charge check

### ISSUE THREAD

**Issue by matteoscrugli** [GameTec-live/ChameleonUltraGUI#525]
**Describe the bug**
When I try to check the battery status via the long press, it happens that the LED flashes red several times (the battery is charged). What does this mean?

**To Reproduce**
1. Long Press B button

**Version info:**
 - OS: [e.g. -
 - App build number: -
 - Connection type: -
 - Chameleon firmware commit: 2.0 (v2.0.0-203-g8a79768)

**Comment by GameTec-live** [comment]
that the adc is still initializing. This is also the reason why, when you immediately connect after wakeup, the battery shows as ? in the app. This isn't a bug. Either just keep the CU awake for a second before long pressing or use the gui...
