### ISSUE TITLE
ios 18.1.1 not found CU

### ISSUE THREAD

**Issue by dittohead** [GameTec-live/ChameleonUltraGUI#540]
**Describe the bug**
Cu gui cant connect to cu via ble after update to ios 18

**To Reproduce**
1. Go to app
2. Click on refresh button and click any button on CU
3. Wait

**Expected behavior**
CU in list, able to connect

**Screenshots**

**Version info:**
 - OS: ios 18.1.1
 - App build number: 1.0.452 appstore (f80487c #538)
 - Connection type: ble
 - Chameleon firmware commit: last master

**Also required**:

- [x] - I've upgraded app to latest app version

- [x] - I've upgraded Chameleon firmware to latest version

- [ ] - I've searched and verified that there is no already created issues 

**Additional context**

**Comment by GameTec-live** [comment]
Hm, works fine on my device. Make sure the CU is woken up when refreshing.

**Comment by dittohead** [comment]
I charges CU and it start to detect, pretty weird
