### ISSUE TITLE
Build linux releases on more stable platform than `ubuntu-latest`

### ISSUE THREAD

**Issue by zeridon** [GameTec-live/ChameleonUltraGUI#67]
Running Ubuntu 20.04 and the build for linux are done on `ubuntu-latest` which has newer glibc

```
./chameleonultragui: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./chameleonultragui)
```

Please reconfigure build to use something more stable (like `ubuntu-20.04`)

**Comment by Foxushka** [comment]
Build works fine on Debian/Arch/Ubuntu (with latest updates). If you run outdated OS - compile app by yourself
