### ISSUE TITLE
Write function for retreiving key from specific slot to stored keys

### ISSUE THREAD

**Issue by GameTec-live** [GameTec-live/ChameleonUltraGUI#7]

**Comment by Foxushka** [comment]
Original firmware doesn't allow retrieving slot information, we should add new function into FW

**Comment by Foxushka** [comment]
Implemented in https://github.com/RfidResearchGroup/ChameleonUltra/pull/56, should be included in https://github.com/GameTec-live/ChameleonUltraGUI/issues/77
