### ISSUE TITLE
Rewrite / imporve slot manager

### ISSUE THREAD

**Issue by GameTec-live** [GameTec-live/ChameleonUltraGUI#77]

**Comment by GameTec-live** [comment]
[sketch.pdf](https://github.com/GameTec-live/ChameleonUltraGUI/files/12209281/sketch.pdf)
<img width="710" alt="Quick sheets - page 1" src="https://github.com/GameTec-live/ChameleonUltraGUI/assets/66077766/7878dbc8-66e7-4af5-85ae-e63a456ce3b1">

**Comment by Foxushka** [comment]
As each slot can handle LF and HF some changes to plan required

**Comment by GameTec-live** [comment]
slot manager good enough, new features will just be built out in eg slot settings, etc.
